import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Script from 'next/script';
import styles from '../../styles/Home.module.css'
import SPage1 from '../page1/Page1.module.css';

const Page2: NextPage = () => {
    return (
    <div className={styles.container}>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
        <h1 className={styles.title}>
            Page 2
        </h1>
        <Script
            id="my-script-page2"
            strategy="lazyOnload"
            dangerouslySetInnerHTML={{
                __html: `
                alert("Result of my script on Page 2");
            `,
            }}
        />
        <Link href="/">
            <a className={SPage1.Link}>
                back to main page
            </a>
        </Link>
        </main>
    </div>
    )
}

export default Page2