import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css'
import SHome from './MainPage.module.css';

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <ul className={SHome.NavBar}>
          <li className={SHome.FirstPageLink}>
            <Link href="/page1">
              <a>
                Page 1 (with Link)
              </a>
            </Link>
          </li>
          <li>
            <button className={SHome.SecondPageButton} onClick={() => router.push('/page2')}> 
              Page 2 (with router)
            </button>
          </li>
        </ul>
      </header>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Home Page
        </h1> 
      </main>
    </div>
  )
}

export default Home
